apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-nalx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-edxv-tenant/rhtap-demo-app/hacbs-test-project-nalx@sha256:4be2d0dc55e6ace2ba6dbc2deee763a7acf2b9108757bd9b5c3330a2fd0404a7
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
