apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-nalx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-edxv-tenant/rhtap-demo-app/hacbs-test-project-nalx@sha256:16898a4176b3931effea94a28217a7790233e454bdd749a00bca0986772b1d7f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
